### ISSUE TITLE
Additional Examples

### ISSUE THREAD

**Issue by mogulman52** [ChrisAlderson/extratorrent-api#1]
Could you add an example like any ebook added in the last 3 days?  Thanks.

**Comment by ChrisAlderson** [comment]
Any ebooks added in the last 3 days is not possible because the parameter `with_words` is required. But you can find all the books added in the last 3 days with the words zeke23.

``` js
extraTorrentAPI.search({
  with_words: "zeke23",
  category: "books",
  added: 3
}).then(res => console.log(res))
  .catch(err => console.error(err));
```

I'll be updating the documentation soon.

**Comment by mogulman52** [comment]
I figured out you can sort of do it.  This '%a%' gives all books that have an 'a' in them.

**Comment by ChrisAlderson** [comment]
I know the `%` is a wildcard for SQL used in the `LIKE` operator. The `%` is a substitute for zero or more characters, but the strange thing is it does not support the `_` wildcard. Also the `[charlist]` operator does not work so searching for `%[a-z]%` will not give the desired result you are looking for. But I could be mistaken and ExtraTorrent does not use an SQL database. 

I'll close this issue and make another one to drop the required `with_words` parameter for advanced search. If you find your solution you can post it there and if you have I will see if I can implement that as a default parameter. Therefor the `with_words` parameter will no longer be required.
