### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by djmbritt** [ChrisAlderson/extratorrent-api#11]
So I am bumping into this error at the moment.

TypeError: Cannot read property '1' of null
    at Website._formatPage (/home/djmbritt/Desktop/kickflix/node_modules/extratorrent-api/lib/Website.js:47:84)
    at get.then.res (/home/djmbritt/Desktop/kickflix/node_modules/extratorrent-api/lib/Website.js:133:25)
    at process._tickCallback (internal/process/next_tick.js:109:7)

Any idea what the issue could be ?

**Comment by jaruba** [comment]
+1 this is broken again:
https://github.com/ChrisAlderson/extratorrent-api/blob/master/lib/Website.js#L47

**Comment by goto-10** [comment]
All the encryption stuff was removed for now. 
For a quick fix, replace lines 46-53. with `const data = res;` in lib/Website.js

**Comment by ChrisAlderson** [comment]
Fixed in https://github.com/ChrisAlderson/extratorrent-api/commit/33f115ba82306070fb6d69d52c2ed3847b070740 and published to npm in v1.1.3.

**Comment by ChrisAlderson** [comment]
Looks like they added the encryption back. Meaning version 1.1.3 doesn't work anymore, but version 1.1.2 does. Therefor version 1.1.3 is deprecated on npm.
