### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Serializator** [ChrisAlderson/extratorrent-api#12]
Whenever a search doesn't result in any torrents being found the `data` variable in the `_formatPage(res, date)` function in the `RSS` module throws a TypeError exception because it tries to access the `length` property in the `data` variable (which is undefined) for the `total_results` property in the object that the function returns.

**Comment by ChrisAlderson** [comment]
Should be fixed in version `1.1.4`.
