### ISSUE TITLE
The results gets mixed-up with the size being interpreted as the date added

### ISSUE THREAD

**Issue by gpapin** [ChrisAlderson/extratorrent-api#3]
This is an example of what I get back from the search : 

```
{ torrent_link: 'https://extratorrent.cc/download/***.torrent',
  language: 'English',
  title: '***',
  sub_category: '***',
  comments: 0,
  size: '7h',
  seeds: NaN,
  leechers: NaN,
  peers: NaN,
  quality: 0 }
```

**Comment by ChrisAlderson** [comment]
What was the query you used to produce this result? Thereby I mean the object or string used as a parameter of the `search` function. This is so I can reproduce the issue.

**Comment by gpapin** [comment]
If you execute this you should see what I mean : 

```
const ExtraTorrentAPI = require('extratorrent-api');
const extraTorrentAPI = new ExtraTorrentAPI();


extraTorrentAPI.search({
    with_words: 'test',
    page: 1,
    category: "other",
    size_type: "mb"
}).then(response => {
    response.results.forEach(torrentInfo => {
        console.log(torrentInfo);
    });
}).catch(err => console.error(err));
```

**Comment by gpapin** [comment]
I've made a fix for this if you are interested.

**Comment by ChrisAlderson** [comment]
Sure, you can submit a PR if you want.

**Comment by gpapin** [comment]
Here you go it's here : https://github.com/ChrisAlderson/extratorrent-api/pull/4

**Comment by ChrisAlderson** [comment]
Updated the version and published this fix to npm. Thanks for you contribution.

**Comment by gpapin** [comment]
No worries, thanks for the module :)
